services:
  - type: web
    name: task-api
    runtime: python
    repo: https://github.com/Dinesh-raya/portfolio
    branch: main
    rootDir: projects/task-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 10000
